[colors.bright]
black= "#414868"
red= "#f7768e"
green= "#9ece6a"
yellow= "#e0af68"
blue= "#7aa2f7"
magenta= "#bb9af7"
cyan= "#7dcfff"
white= "#c0caf5"

[colors.normal]
black= "#15161e"
red= "#f7768e"
green= "#9ece6a"
yellow= "#e0af68"
blue= "#7aa2f7"
magenta= "#bb9af7"
cyan= "#7dcfff"
white= "#a9b1d6"

[colors.primary]
#background = "#000000"
background = "#1a1b26"
foreground = "#c0caf5"

[font]
size = 12.0

[font.bold]
family = "SourceCodePro"
style = "Bold"

[font.bold_italic]
family = "SourceCodePro"
style = "Bold Italic"

[font.italic]
family = "SourceCodePro"
style = "Italic"

[font.normal]
family = "SourceCodePro"
style = "Regular"

[cursor.style]
blinking = "Always"
shape = "Underline"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "Z"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = false
opacity = 1
title = "Alacritty"
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5
