#!/bin/zsh

alias ls='ls --color=auto'
alias ll='LC_COLLATE=C ls -Alh --group-directories-first'
alias grep='grep --color=auto'
alias diff="diff --color=auto"
alias cp='cp -rfv'
alias mv='mv -fv'
alias rm='rm -rfv'
alias mkdir='mkdir -pv'
alias wgcc='x86_64-w64-mingw32-gcc'
alias wmake='x86_64-w64-mingw32-make'
alias cmd='wine cmd'
alias nv='nvim'
alias snv='sudo nvim'
alias slf='sudo lf'
alias pac='sudo pacman'
alias deb='sudo arch-chroot ~/.roots/debian /bin/zsh -c "cd /home/marko && /bin/su marko"'
alias dot='nvim ~/.dotfiles'
alias open='$OPENER'

ex() {
	if [ -f $1 ] ; then
		case $1 in
			*.tar.bz2)   tar xjf $1     ;;
			*.tar.gz)    tar xzf $1     ;;
			*.bz2)       bunzip2 $1     ;;
			*.rar)       unrar e $1     ;;
			*.gz)        gunzip $1      ;;
			*.tar)       tar xf $1      ;;
			*.tbz2)      tar xjf $1     ;;
			*.tgz)       tar xzf $1     ;;
			*.zip)       unzip $1       ;;
			*.Z)         uncompress $1  ;;
			*.7z)        7z x $1        ;;
			*)     echo "'$1' cannot be extracted via extract()" ;;
		esac
	else
		echo "'$1' is not a valid file"
	fi
}
