#!/bin/sh

# copy config files
mv ~/.config ~/.old_config
mv ~/.local ~/.old_local
mv ~/.mozilla ~/.old_mozilla

mkdir -p ~/Documents
mkdir -p ~/Downloads
mkdir -p ~/Music
mkdir -p ~/Pictures/screenshots
mkdir -p ~/.local/share/zsh
mkdir -p ~/.local/share/mpd

cp -rf ./icons ~/.local/share/
cp -rf ./themes ~/.local/share/

sudo pacman --noconfirm -Syu

# hyprland
sudo pacman -S --noconfirm hyprland hyprpaper hypridle hyprlock wl-clipboard \
	xdg-desktop-portal-gtk xdg-desktop-portal-wlr vulkan-radeon libva-mesa-driver
# apps
sudo pacman -S --noconfirm zsh alacritty neovim valgrind htop lf fzf zip unzip stow \
	rustup waybar dunst swayimg ncmpcpp mpd mpc mpv man-db fuzzel flatpak firefox

#link config
stow --no-folding --ignore="icons|themes|rules|install|system" --adopt .

# flatpaks
sudo flatpak override --filesystem=xdg-data/themes
sudo flatpak override --filesystem=xdg-data/icons
sudo flatpak override --env=GTK_THEME=Tokyonight

sudo systemctl enable seatd.service
sudo systemctl mask backlight@.service
sudo systemctl mask --global at-spi-dbus-bus.service

#aur
git clone http://aur.archlinux.org/yay.git
cd yay
makepkg -si --noconfirm
cd ..

yay -S --noconfirm hyprshot ttf-exo-2 ttf-sourcecodepro-nerd

#theme
gsettings set org.gnome.desktop.interface gtk-theme 'Orchis-Dark'
gsettings set org.gnome.desktop.interface font-name 'Exo 2 11'
gsettings set org.gnome.desktop.interface cursor-theme 'Future-dark-cursors'

# shell
sudo ./system.sh $USER
chsh -s /bin/zsh

reboot
