#!/bin/sh

mv ~/.config ~/.old_config
mv ~/.local ~/.old_local

mkdir -p ~/pictures/screenshots
mkdir -p ~/documents
mkdir -p ~/downloads

mkdir -p ~/.config
mkdir -p ~/.local/share/zsh
mkdir -p ~/.local/share/mpd

git clone http://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si --noconfirm
cd ..
rm -rf paru-bin

paru --noconfirm -Syu

paru -S --noconfirm hyprland hypridle hyprlock hyprshot hyprpicker waybar dunst wl-clipboard mpv fuzzel \
	xdg-desktop-portal-gtk xdg-desktop-portal-wlr vulkan-radeon libva-mesa-driver mesa-vdpau bluez bluez-utils

paru -S --noconfirm zsh ghostty zellij htop neovim yazi ripgrep fd lsd \
	fzf bat zip unzip unarchiver stow ncmpcpp mpd mpc man-db flatpak 

paru -S --noconfirm ttf-exo-2 ttf-nerd-fonts-symbols

stow --no-folding --adopt --target=$HOME/.config config
stow --no-folding --adopt --target=$HOME/.local local
ln -s /usr/share/themes ~/.local/share/themes
ln -s /usr/share/icons ~/.local/share/icons

sudo systemctl enable seatd.service
sudo systemctl mask backlight@.service
sudo systemctl enable bluetooth.service

update-desktop-database ~/.local/share/applications/

flatpak override --user --filesystem=xdg-data/themes
flatpak override --user --filesystem=xdg-data/icons
flatpak override --user --env=GTK_THEME=Adwaita
flatpak override --user --env=XCURSOR_THEME=Adwaita
flatpak override --user --env=XCURSOR_SIZE=24
flatpak override --user --socket=wayland

sudo ./system $USER
chsh -s /bin/zsh
