#!/bin/sh

[ ! -f "utils" ] && echo "Missing: utils" && exit 1
source ./utils

[ ! -f "packages" ] && echo "Missing: packages" && exit 1
source ./packages

mv ~/.config ~/.old_config
mv ~/.local ~/.old_local

mkdir -p ~/pictures/screenshots
mkdir -p ~/pictures/videos
mkdir -p ~/documents
mkdir -p ~/downloads

mkdir -p ~/.config
mkdir -p ~/.local/share/zsh
mkdir -p ~/.local/share/mpd

if ! command -v paru &> /dev/null; then
	git clone http://aur.archlinux.org/paru-bin.git >/dev/null 2>&1
	cd paru-bin
	makepkg -si --noconfirm >/dev/null 2>&1
	cd ..
	rm -rf paru-bin
fi

paru --noconfirm -Syu >/dev/null 2>&1

echo "Installing packages..."
install_packages "${ARCH[@]}"

echo "Installing flatpaks..."
install_flatpaks "${FLATPAKS[@]}"

stow --no-folding --adopt --target=$HOME/.config config
stow --no-folding --adopt --target=$HOME/.local local
ln -s /usr/share/themes ~/.local/share/themes
ln -s /usr/share/icons ~/.local/share/icons

sudo systemctl enable seatd.service
sudo systemctl enable bluetooth.service
sudo systemctl enable power-profiles-daemon.service
systemctl enable --user mpd

update-desktop-database ~/.local/share/applications/

flatpak override --user --filesystem=xdg-data/themes
flatpak override --user --filesystem=xdg-data/icons
flatpak override --user --env=GTK_THEME=Adwaita
flatpak override --user --env=ICON_THEME=Adwaita
flatpak override --user --env=XCURSOR_THEME=Adwaita
flatpak override --user --env=XCURSOR_SIZE=24
flatpak override --user --socket=wayland

flatpak override --user com.valvesoftware.Steam \
  --env=STEAM_FORCE_DESKTOPUI_SCALING=2 \
  --env=GDK_SCALE=2 \
  --env=QT_SCALE_FACTOR=2

root_setup "$USER"
