#!/bin/sh

is_installed() {
	pacman -Qi "$1" &> /dev/null || pacman -Qg "$1" &> /dev/null
}

install_packages() {
	local packages=("$@")
	local to_install=()

	for pkg in "${packages[@]}"; do
		if ! is_installed "$pkg"; then
			to_install+=("$pkg")
		fi
	done

	if [ ${#to_install[@]} -ne 0 ]; then
		echo "Installing: ${to_install[*]}"
		paru -S --noconfirm --quiet --skipreview --cleanafter "${to_install[@]}" >/dev/null 2>&1
	fi
} 

install_flatpaks() {
	local packages=("$@")

	for pkg in "${packages[@]}"; do
		if ! flatpak list | grep -i "$pkg" &> /dev/null; then
			echo "Installing Flatpak: $pkg"
			flatpak install --noninteractive "$pkg" >/dev/null 2>&1
		else
			echo "Flatpak already installed: $pkg"
		fi
	done
}

root_setup() {
	if [[ "$EUID" -ne 0 ]]; then
		sudo bash -c "source $(realpath "${BASH_SOURCE[0]}") && root_setup $1"
		return
	fi

    local sudo_line="$1 ALL=(ALL:ALL) NOPASSWD: ALL"
    grep -qxF "$sudo_line" /etc/sudoers || echo "$sudo_line" >> /etc/sudoers

    local bash_line='[ -f "$HOME/.config/bash/bashrc" ] && source "$HOME/.config/bash/bashrc"'
    grep -qxF "$bash_line" /etc/bash.bashrc || echo "$bash_line" >> /etc/bash.bashrc

	usermod -a -G video $1
	usermod -a -G seat $1
	cp rules/* /etc/udev/rules.d/
	ln -s /home/$1/.config /root/.config
}
