let skip_defaults_vim=1

set viminfo=""

set autoindent
set expandtab
set shiftwidth=4
set smarttab
set tabstop=4

set hlsearch
set ignorecase
set incsearch

set mouse=a
set scrolloff=5
let &t_EI .= "\<Esc>[3 q"
let &t_SI .= "\<Esc>[3 q"
let &t_SR .= "\<Esc>[3 q"

set number
set laststatus=2

set background=dark
set t_Co=256
hi Visual ctermbg=8
hi LineNr cterm=bold ctermfg=7 ctermbg=8
hi StatusLine ctermfg=8 ctermbg=7

syntax on

set statusline=
set statusline+=\ 
set statusline+=\ %f
set statusline+=\ %m
set statusline+=%=
set statusline+=\ %y
set statusline+=\ %{&fileencoding?&fileencoding:&encoding}
set statusline+=\[%{&fileformat}\]
set statusline+=\ %p%%
set statusline+=\ %l:%c
set statusline+=\ 

map <C-c> y: call system("xclip -i -selection clipboard", getreg("\""))<CR>
map <C-v> :call setreg("\"",system("xclip -o -selection clipboard"))<CR>p
map <C-a> ggVG

