#! /bin/zsh

set ratios 1:2:3
set drawbox true
set hidden true
set ignorecase true
set icons true
set shell zsh
set mouse true
set scrolloff 10
set cursorpreviewfmt "\033[7;2m"

map a :push %mkdir<space>
map b :push %touch<space>
map <delete> delete
map <tab> shell
map x $$f
map X !$f
map <enter> $$EDITOR "$f"
map e extract

cmd open &{{
	case $(file --mime-type -Lb $f) in
		text/*) lf -remote "send $id \$$EDITOR \$fx";;
		*) for f in $fx; do $OPENER $f > /dev/null 2> /dev/null & done;;
	esac
}}

cmd extract ${{
set -f
case $f in
	*.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
	*.tar.gz|*.tgz) tar xzvf $f;;
	*.tar.xz|*.txz) tar xJvf $f;;
	*.zip) unzip $f;;
	*.rar) unrar x $f;;
	*.7z) 7z x $f;;
	esac
}}
