monitor= eDP-1, 2880x1800@90, 0x0, 1.5

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP SWAYSOCK
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = brillo -S 30.2
exec-once = sudo cpuset powersave
exec-once = mpd
exec-once = waybar

exec = gsettings set org.gnome.desktop.interface gtk-theme "Tokyonight"
exec = gsettings set org.gnome.desktop.interface icon-theme "Fluent-dark"
exec = gsettings set org.gnome.desktop.interface cursor-theme "Future-dark-cursors"
exec = gsettings set org.gnome.desktop.interface font-name "Exo 2 12"
