#!/bin/bash
bat=$(cat /sys/class/power_supply/BAT0/capacity)
ac=$(cat /sys/class/power_supply/AC0/online)
if (($ac == 1));
then 
	printf " "
elif (($bat < 20));
then
	printf "  "
elif (($bat < 40));
then
	printf "  "
elif (($bat < 60));
then
	printf "  "
elif (($bat < 80));
then
	printf "  "
else
	printf "  "
fi

printf $bat
