#!/bin/sh
ac=$(cat /sys/class/power_supply/AC0/online)
if (($ac != 1));
then
	guvernor=$( cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference )
fi
echo "{\"text\": \"$guvernor\", \"class\": \"$guvernor\", \"alt\": \"$guvernor\"}"
