# BACKGROUND
background {
    monitor =
    color = rgb(10, 15, 15)
}

# GENERAL
general {
    grace = 0
    disable_loading_bar = true
	hide_cursor = true
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(61afefff)
    inner_color = rgba(0, 0, 0, 1)
    font_color = rgb(192, 202, 245)
    fade_on_empty = false
    font_family = Exo 2
    placeholder_text = <i><span foreground="##c0caf5">Input Password...</span></i>
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%-I:%M%p")"
    color = rgb(192, 202, 245)
    font_size = 120
    font_family = Exo 2 ExtraBold
    position = 0, -500
    halign = center
    valign = top
}

# USER
label {
    monitor =
    text = cmd[update:0] echo $(tr a-z- A-Z_ <<< $USER)
    color = rgb(192, 202, 245)
    font_size = 32
    font_family = Exo 2 Bold
    position = 0, -50
    halign = center
    valign = center
}
