#!/bin/zsh

alias ls='ls --color=auto'
alias ll='LC_COLLATE=C ls -al --group-directories-first'
alias grep='grep --color=auto'
alias diff="diff --color=auto"
alias cp='cp -rfv'
alias mv='mv -fv'
alias rm='rm -rfv'
alias mkdir='mkdir -pv'
alias wgcc='x86_64-w64-mingw32-gcc'
alias wmake='x86_64-w64-mingw32-make'
alias wine='flatpak run org.winehq.Wine'
alias cmd='flatpak run org.winehq.Wine cmd'
alias nv='nvim'
alias pac='sudo pacman'
