#!/bin/zsh

alias ls="LC_COLLATE=C ls -A --group-directories-first --color=auto"
alias ll="ls -oh"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias cp="cp -rfv"
alias mv="mv -fv"
alias rm="rm -rfv"
alias mkdir="mkdir -pv"
alias pac="paru"
alias fm="yazi"
alias o="$OPENER"
alias wg="ssh student@student-vm-0074.ec.gw.tc -t bash --login"

function chpwd() {
	ls
	tmux refresh-client -S
}
