#!/bin/zsh

function tmux_window() {
    if [ -n "$TMUX" ]; then
		# tab_name=''
		if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
			tab_name=$(basename "$(git rev-parse --show-toplevel)")
		else
			tab_name=$PWD
			if [[ $tab_name == $HOME ]]; then
				tab_name="~"
			else
				tab_name=${tab_name##*/}
			fi
		fi
		tmux select-pane -T "$tab_name"
    fi
}

tmux_window
chpwd_functions+=(tmux_window)
