#!/bin/zsh

PROMPT='%B%F{blue}󰣇 %F{green}%1~%f > %b'

export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR=/run/user/$UID

HISTFILE=$XDG_DATA_HOME/zsh/histfile
HISTSIZE=1000000
SAVEHIST=1000000

export EDITOR=nvim
export TERMINAL=alacritty
export BROWSER=firefox
export OPENER=xdg-open

export TERM=xterm
export WINEPREFIX=$HOME/.local/wine
export WINEDEBUG=-all
export XINITRC=$HOME/.config/x/xinitrc
export GTK_USE_PORTAL=1
export NO_AT_BRIDGE=1
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export GTK_A11Y=none
